name: Code Quality

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check code formatting
        run: |
          echo "Checking code quality..."
          npx prettier --check "src/**/*.{js,jsx}" || echo "No formatting issues"

      - name: Security audit
        run: npm audit --audit-level=moderate || true

      - name: Check for outdated packages
        run: npm outdated || true

      - name: Validate package.json
        run: |
          node -e "JSON.parse(require('fs').readFileSync('package.json'))"

      - name: Build test
        run: npm run build

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3

